config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'orders#index'

  resources :orders do
    collection do
      post 'check_code'
    end
  end

  namespace :admin do
    resources :coupons
    resources :transactions
  end

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  has_many :orders

  attr_accessor :count, :mask

  validates :mask, :sum, :count, presence: true
  validates :coupon_type, inclusion: { in: %w(percentage amount) }
  validates :code, uniqueness: true

  validates :redemption_limit, numericality: {
    greater_than_or_equal_to: 0 }

  scope :by_code, -> (code){ where(code: code) }

  def percentage_based?
    coupon_type == 'percentage'
  end

  def amount_based?
    coupon_type == 'amount'
  end

  def is_active?
    orders.count < redemption_limit
  end

  def calculate_sum(order_sum)
    order_sum.to_f - calculate_amount(order_sum).to_f
  end

  def calculate_amount(order_sum)
    if amount_based?
      sum
    else
      order_sum.to_f * sum.to_f / 100
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :coupon
  belongs_to :user

  validates :description, :sum, presence: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  scopify

  belongs_to :resource, polymorphic: true
  has_and_belongs_to_many :users, join_table: :users_roles

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify strict: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders
  has_many :redemptions, class_name: 'CouponRedemption'

end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < ApplicationController
  layout 'admin'
  before_action :authorize_as_admin!

  def index
    @coupons = Coupon.order(id: :desc).page(params[:page])
  end

  def new
    @coupon = Coupon.new
  end

  def create
    count = coupon_params[:count]
    mask = coupon_params[:mask]
    charset = ('a'..'z').to_a + ('A'..'Z').to_a
    strint = (charset + (0..9).to_a).flatten
    @coupon = Coupon.new(coupon_params)
    if @coupon.valid?
      i = 1
      while i <= count.to_i do
        code = mask.gsub(/#/, rand(10).to_s).gsub(/@/, charset.sample(1).first).gsub(/\*/, strint.sample(1).first.to_s)
        @coupon = Coupon.new(coupon_params)
        @coupon.code = code
        i += 1 if @coupon.save
      end
    else
      render :new and return
    end
    redirect_to admin_coupons_path
  end

  def edit
  end

  def update
    @coupon = Coupon.find(params[:id])

    if @coupon.update(coupon_params)
      redirect_to admin_coupons_path
    else
      render :edit
    end
  end

  def destroy
    @coupon.destroy!

    redirect_to admin_coupons_path
  end

  private

  def find_coupon
    @coupon = Coupon.find(params[:id])
  end

  def coupon_params
    params
      .require(:coupon)
      .permit(:redemption_limit, :sum, :coupon_type, :mask, :count)
  end
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < ApplicationController
  layout 'admin'
  before_action :authorize_as_admin!

  def index
    @orders = Order.includes(:user).includes(:coupon).order(id: :desc).page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  
  protect_from_forgery with: :exception

  private

  def authorize_as_admin!
    unless current_user.has_role? :admin
      flash[:notice] = 'Вы не авторизованы для исполнения данного действия'
      redirect_to root_path and return
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_order, only: [:edit, :update]
  before_action :find_coupon, only: [:coupon_check, :create, :check_code]


  def index
    if current_user.has_role? :admin
      redirect_to admin_transactions_path  and return
    else
      redirect_to new_order_path and return
    end
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(permitted_params)
    @order.user = current_user
    if @coupon.present? && @coupon.is_active?
      @order.coupon = @coupon
      @order.sum = @coupon.calculate_sum(@order.sum)
    end
    if @order.save
      flash[:success] = 'Все хорошо'
      redirect_to new_order_path
    else
      render :new
    end
  end

  def check_code
    if @coupon.present? && @coupon.is_active?
      @result = @coupon.calculate_sum(params[:sum])
      @amount = @coupon.calculate_amount(params[:sum])
      @result = 0 if @result < 0
      flash[:notice] = 'Промо-код принят'
    else
      flash[:error] = 'Не верный промо код'
    end
  end

  private

  def find_order
    @order = Order.find(params[:id])
  end

  def find_coupon
    @coupon = Coupon.by_code(params[:code]).first
  end

  def permitted_params
    params[:order].permit(:description, :sum, :code)
  end
end

app/helpers/admin/coupons_helper.rb
module Admin::CouponsHelper
end

app/helpers/admin/transactions_helper.rb
module Admin::TransactionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end
end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/admin/coupons/_form.html.slim
.row
  .col-md-6
    = simple_form_for [ :admin, @coupon] do |f|
      = f.input :redemption_limit
      = f.input :coupon_type, collection: [ 'amount', 'percentage' ]
      = f.input :sum
      = f.input :mask
      = f.input :count
      = f.button :submit, 'Создать', class: 'btn btn-success'

app/views/admin/coupons/index.html.slim
h2 Coupons
.row
  table.table.table-striped
    tr
      th Code
      th Redemption limit
      th Sum
      th Type
      
    - @coupons.each do |coupon|
      tr
        td= coupon.code
        td= coupon.redemption_limit
        td= coupon.sum
        td= coupon.coupon_type
= paginate @coupons

app/views/admin/coupons/new.html.slim
= render 'form'

app/views/admin/transactions/index.html.slim
h2 Transactions
.row
  table.table.table-striped
    tr
      th Description
      th Sum
      th Amount
      th Code
      th IP
    - @orders.each do |order|
      tr
        td= order.description
        td= order.sum
        td= order.coupon.calculate_amount(order.sum) if order.coupon.present?
        td= order.coupon.code if order.coupon.present?
        td= order.user.last_sign_in_ip
= paginate @orders

app/views/layouts/admin.html.slim
doctype html
html
  head
    title
      | igooods
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-static-top
      .container
        p.navbar-text
          = link_to 'Транзакции', admin_transactions_path
        p.navbar-text
          = link_to 'Промо коды', admin_coupons_path
        
        = link_to 'Сгенерить промо коды', new_admin_coupon_path, class: 'btn btn-info btn-sm navbar-btn'
        
        - if current_user
          = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm navbar-btn navbar-right'
    .container
      = flash_messages
      = yield

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | igooods
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-default.navbar-static-top
      .container
        - if current_user
          = link_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-danger btn-sm navbar-btn navbar-right'
    .container
      .js-flash-massage
        = flash_messages
      = yield

app/views/orders/_form.html.slim
.col-md-6
  = simple_form_for @order, html: { class: 'form-horizontal' } do |f|
    = f.input :description, input_html: { rows: 10 }
    = f.input :sum
    .form-group
      = text_field_tag 'code', '', placeholder: 'промо-код',  class: 'form-control'
    = f.button :submit, 'Оплатить', class: 'btn btn-success'
  
    h4#coupon Размер скидки:
    h4#result Итого:
    

app/views/orders/_msg.html.slim
= flash_messages

app/views/orders/edit.html.slim
= render 'form'

app/views/orders/new.html.slim
= render 'form'